Add and Remove
sheylaPozo/todolist pull request #4
Opened 2021-07-23 21:32 UTC by sheylaPozo

- [ ] Remove all hardcoded items from the tasks array.
- [ ] Create a new JavaScript file for the new functionality.

2021-07-23 22:46 UTC, henatan99 requested changes
Hi @sheylaPozo , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
- [ ] Please try to add a more descriptive summary to your PR. :pray: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 22:46 UTC, henatan99 commented on src/dragAndDrop.js
> +  });
- [ ] Please remove this eslint-disable command and give return a value for the savedList.map function.

2021-07-23 22:46 UTC, henatan99 commented on src/addAndRemove.js
> +      p.addEventListener('keydown', (e) => {
- [ ] I don't think the 'keydown' event is right here. Just key down doesn't make the description editable. There is a bug that doesn't let the description text be edited unless the `i` tag is clicked. Please, kindly fix this bug.

2021-07-24 00:03 UTC, sheylaPozo commented on src/dragAndDrop.js
> +  });
ok fixed it

2021-07-24 00:04 UTC, sheylaPozo commented on src/addAndRemove.js
> +      p.addEventListener('keydown', (e) => {
Fixed it

2021-07-24 00:29 UTC, de-scholar approved these changes
Hi @sheylaPozo :handshake:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

:warning: Anyways your live demo link from the readme file is showing a different page (it displays your readme file) kindly fix it in order to make your repo more professional

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-24 00:33 UTC, sheylaPozo commented
Thank you :) I will

2021-07-24 00:33 UTC, merged